In [1]:
import pandas as pd
import numpy as np

## Problem 1
## (a)

## P{Label = Large} = 70/100 =0.7
## P{Label = Jumble and Weight = 4g} = 5/100 =0.05
## P{Weight = 2g | Label = Large} = 40/48 = 5/6
## P{Weight = 2g} = 48/100 = 0.48
## P{Weight = 2g | Label = Jumble} = 8/30 = 4/15
## P{Label = Jumble | Weight = 2g } = 8/48 = 1/6

## (b)

## Label\Weight   1g  2g   3g       4g
##      Large            1  5/6 10/27   0.5
##    Jumble           0  1/6 17/27   0.5
## Decision (L/J)   L    L      J        L

## (c)

## G\D        Large Jumble
## Large       60       10
## Jumble    13       17

## P{Mis-classification} = 0.23

## Problem 2
## (a)

In [8]:
data = pd.read_csv('iris.csv',header=None)

In [9]:
data

0    1    2    3  4
0    5.1  3.5  1.4  0.2  1
1    4.9  3.0  1.4  0.2  1
2    4.7  3.2  1.3  0.2  1
3    4.6  3.1  1.5  0.2  1
4    5.0  3.6  1.4  0.2  1
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  3
146  6.3  2.5  5.0  1.9  3
147  6.5  3.0  5.2  2.0  3
148  6.2  3.4  5.4  2.3  3
149  5.9  3.0  5.1  1.8  3

[150 rows x 5 columns]

In [13]:
data_f = data.iloc[:, 0:4]

In [14]:
data_f.mean()

0    5.843333
1    3.054000
2    3.758667
3    1.198667
dtype: float64

In [15]:
data_f.std()

0    0.828066
1    0.433594
2    1.764420
3    0.763161
dtype: float64

## (b)

In [16]:
data_f.T

0    1    2    3    4    5    6    7    8    9    ...  140  141  142  143  \
0  5.1  4.9  4.7  4.6  5.0  5.4  4.6  5.0  4.4  4.9  ...  6.7  6.9  5.8  6.8   
1  3.5  3.0  3.2  3.1  3.6  3.9  3.4  3.4  2.9  3.1  ...  3.1  3.1  2.7  3.2   
2  1.4  1.4  1.3  1.5  1.4  1.7  1.4  1.5  1.4  1.5  ...  5.6  5.1  5.1  5.9   
3  0.2  0.2  0.2  0.2  0.2  0.4  0.3  0.2  0.2  0.1  ...  2.4  2.3  1.9  2.3   

   144  145  146  147  148  149  
0  6.7  6.7  6.3  6.5  6.2  5.9  
1  3.3  3.0  2.5  3.0  3.4  3.0  
2  5.7  5.2  5.0  5.2  5.4  5.1  
3  2.5  2.3  1.9  2.0  2.3  1.8  

[4 rows x 150 columns]

In [18]:
data_t = data_f.T
m_x = data_t.mean(axis=1)

In [19]:
m_x

0    5.843333
1    3.054000
2    3.758667
3    1.198667
dtype: float64

In [20]:
data_f.cov()

0         1         2         3
0  0.685694 -0.039268  1.273682  0.516904
1 -0.039268  0.188004 -0.321713 -0.117981
2  1.273682 -0.321713  3.113179  1.296387
3  0.516904 -0.117981  1.296387  0.582414

## (c)

In [22]:
cov = data_f.cov()
eigva, eigve = np.linalg.eig(cov)

In [23]:
## eigenvalues
eigva

array([4.22484077, 0.24224357, 0.07852391, 0.02368303])

In [24]:
## eigenvectors
eigve

array([[ 0.36158968, -0.65653988, -0.58099728,  0.31725455],
       [-0.08226889, -0.72971237,  0.59641809, -0.32409435],
       [ 0.85657211,  0.1757674 ,  0.07252408, -0.47971899],
       [ 0.35884393,  0.07470647,  0.54906091,  0.75112056]])

In [28]:
svdu, svda, svdv = np.linalg.svd(cov)

In [29]:
## left singular vector matrix
svdu

array([[-0.36158968, -0.65653988,  0.58099728,  0.31725455],
       [ 0.08226889, -0.72971237, -0.59641809, -0.32409435],
       [-0.85657211,  0.1757674 , -0.07252408, -0.47971899],
       [-0.35884393,  0.07470647, -0.54906091,  0.75112056]])

In [30]:
## singular values
svda

array([4.22484077, 0.24224357, 0.07852391, 0.02368303])

In [31]:
## right singular vector matrix
svdv

array([[-0.36158968,  0.08226889, -0.85657211, -0.35884393],
       [-0.65653988, -0.72971237,  0.1757674 ,  0.07470647],
       [ 0.58099728, -0.59641809, -0.07252408, -0.54906091],
       [ 0.31725455, -0.32409435, -0.47971899,  0.75112056]])

## In this case, matrix C is full rank. The singular values are equal to the eigenvalues and the left singular vector matrix is equal to the eigenvector matrix. This is because the C is symmetric and positive definite.