## Problem 1

In [1]:
import numpy as np

In [11]:
X = np.mat([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
w = np.mat([[-0.1],[0.3],[-0.2]])
d = np.mat([[0],[0],[0],[1]])

In [6]:
u = X.dot(w)

In [7]:
u

matrix([[-1.00000000e-01],
        [-3.00000000e-01],
        [ 2.00000000e-01],
        [-2.77555756e-17]])

In [30]:
def sigmoid(x):
    return 1. / (1 + np.exp(-x))

def dfsigmod(x):
    return np.multiply(sigmoid(x),1-sigmoid(x))

In [16]:
z = sigmoid(u)

In [17]:
z

matrix([[0.47502081],
        [0.42555748],
        [0.549834  ],
        [0.5       ]])

In [18]:
e = d - z

In [19]:
e

matrix([[-0.47502081],
        [-0.42555748],
        [-0.549834  ],
        [ 0.5       ]])

In [32]:
delta = np.multiply(dfsigmod(u),e)

In [33]:
delta

matrix([[-0.11845881],
        [-0.10403106],
        [-0.13609303],
        [ 0.125     ]])

In [35]:
lr = 0.1

In [36]:
w = w + lr * X.T.dot(delta)

In [37]:
w

matrix([[-0.12335829],
        [ 0.2988907 ],
        [-0.19790311]])

## Problem 2

## $\delta_{i}^{(l)}(k)=\frac{\partial E}{\partial u_i^{(l)}(k)}$$=f^{'}(u_i^{(l)}(k))·\sum_{m=1}^{N(l+1)}\delta_{m}^{(l+1)}(k)·\frac{\partial u_m^{(l+1)}(k)}{\partial z_i^{(l)}(k)}$ $=f^{'}(u_i^{(l)}(k))·\sum_{m=1}^{N(l+1)}w_{im}^{(l+1)}(k)·\delta_m^{(l+1)}(k)$

## where for the output layer:

## $\delta_{1}^{(3)}(k)=f^{'}(u_1^{(3)}(k))·[z_{1}^{(3)}(k)-d_{1}(k)]$

## $\delta_{2}^{(3)}(k)=f^{'}(u_2^{(3)}(k))·[z_{2}^{(3)}(k)-d_{2}(k)]$

## for $\delta_{1}^{(2)}(k)=\frac{\partial E}{\partial u_1^{(2)}(k)}$

## $\delta_{1}^{(2)}(k)= f^{'}(u_1^{(2)}(k))·\sum_{m=1}^{N(3)}w_{1m}^{(3)}(k)·\delta_m^{(3)}(k)$

## $N(3)=2$

## $\delta_{1}^{(2)}(k)= f^{'}(u_1^{(2)}(k))·\sum_{m=1}^{2}w_{1m}^{(3)}(k)·\delta_m^{(3)}(k)$

## $\delta_{1}^{(2)}(k)= f^{'}(u_1^{(2)}(k))·(w_{1,1}^{(3)}(k)·\delta_1^{(3)}(k)+w_{1,2}^{(3)}(k)·\delta_2^{(3)}(k))$