In [1]:
import pandas as pd
import numpy as np

In [3]:
outr = pd.read_csv('outr.csv', header=None).to_numpy()

In [4]:
outv = pd.read_csv('outv.csv', header=None).to_numpy()

## (a)

In [6]:
vvote = list()
for i in range(outv.shape[0]):
    vvote.append(np.argmax(np.bincount(outv[i,0:3].astype(int))))
vvote = np.array(vvote)

In [7]:
from sklearn.metrics import confusion_matrix

In [11]:
vvote != outv[:,3]

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [12]:
vvote != outv[:,4]

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False])

In [15]:
Cmatvote = confusion_matrix(outv[:,3], vvote)
print("Confusion Matrix: ")
print(Cmatvote)

Confusion Matrix: 
[[15  0  0]
 [ 0 16  0]
 [ 0  0 14]]


In [13]:
Cmatvote = confusion_matrix(outv[:,4], vvote)
print("Confusion Matrix: ")
print(Cmatvote)

Confusion Matrix: 
[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]


## (b)

In [21]:
combination = {}
df = pd.DataFrame(outr[:,0:3])
for index, row in df.iterrows():
    comb = [int(x) for x in row]
    comb = str(comb)
    if comb not in combination.keys():
        combination[comb] = [int(outr[:,4][index])]
    else:
        if int(outr[:,4][index])   not in combination[comb]:
            combination[comb].append(int(outr[:,4][index]))
combination

{'[1, 1, 1]': [1],
 '[2, 2, 2]': [2, 3],
 '[3, 3, 3]': [2, 3],
 '[2, 3, 2]': [2],
 '[3, 2, 2]': [2],
 '[2, 3, 3]': [2, 3],
 '[2, 2, 3]': [3]}

In [47]:
combination = []
df = pd.DataFrame(outr[:,0:3])
for index, row in df.iterrows():
    comb = [int(x) for x in row]
    if comb not in combination:
        combination.append(comb)
combination

[[1, 1, 1], [2, 2, 2], [3, 3, 3], [2, 3, 2], [3, 2, 2], [2, 3, 3], [2, 2, 3]]

In [48]:
label = [1,2,3,2,2,2,3]

In [49]:
outr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 2],
       [2, 2, 2,

In [50]:
assign = []
for i in range(outr[:,0:3].shape[0]):
    for j in range(len(label)):
        if (outr[i,0:3] == np.array(combination[j])).all():
            assign.append(label[j])

In [51]:
np.array(assign)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [55]:
outr[:,4]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [56]:
Cmatmanual = confusion_matrix(outr[:,4], np.array(assign))
print("Confusion Matrix: ")
print(Cmatmanual)

Confusion Matrix: 
[[35  0  0]
 [ 0 34  1]
 [ 0  2 33]]
