In [1]:
import pandas as pd
import numpy as np
import scipy as sp
from sklearn.model_selection import train_test_split

## Problem 1
## (a)

In [2]:
data = pd.read_csv('iris.csv',header=None)
data

0    1    2    3  4
0    5.1  3.5  1.4  0.2  1
1    4.9  3.0  1.4  0.2  1
2    4.7  3.2  1.3  0.2  1
3    4.6  3.1  1.5  0.2  1
4    5.0  3.6  1.4  0.2  1
..   ...  ...  ...  ... ..
145  6.7  3.0  5.2  2.3  3
146  6.3  2.5  5.0  1.9  3
147  6.5  3.0  5.2  2.0  3
148  6.2  3.4  5.4  2.3  3
149  5.9  3.0  5.1  1.8  3

[150 rows x 5 columns]

In [3]:
iris_train1,iris_test1 = train_test_split(data[data.iloc[:,4]==1], train_size = 0.5)
iris_train2,iris_test2 = train_test_split(data[data.iloc[:,4]==2], train_size = 0.5)
iris_train3,iris_test3 = train_test_split(data[data.iloc[:,4]==3], train_size = 0.5)

In [4]:
iris_train = pd.concat([iris_train1, iris_train2, iris_train3])
iris_test = pd.concat([iris_test1, iris_test2, iris_test3])

In [5]:
iris_train

0    1    2    3  4
5    5.4  3.9  1.7  0.4  1
15   5.7  4.4  1.5  0.4  1
10   5.4  3.7  1.5  0.2  1
6    4.6  3.4  1.4  0.3  1
17   5.1  3.5  1.4  0.3  1
..   ...  ...  ...  ... ..
117  7.7  3.8  6.7  2.2  3
139  6.9  3.1  5.4  2.1  3
118  7.7  2.6  6.9  2.3  3
130  7.4  2.8  6.1  1.9  3
145  6.7  3.0  5.2  2.3  3

[75 rows x 5 columns]

## $\mu_k(k=1)$

In [6]:
u1 = iris_train.iloc[0:25,2:4].mean()
u1

2    1.468
3    0.272
dtype: float64

## $\mu_k(k=2)$

In [7]:
u2 = iris_train.iloc[25:50,2:4].mean()
u2

2    4.304
3    1.356
dtype: float64

## $\mu_k(k=3)$

In [8]:
u3 = iris_train.iloc[50:75,2:4].mean()
u3

2    5.560
3    2.064
dtype: float64

## $\Sigma_k(k=1)$

In [9]:
iris_train.iloc[0:25,2:4].cov()

2         3
2  0.033100  0.009483
3  0.009483  0.014600

## $\Sigma_k(k=2)$

In [10]:
iris_train.iloc[25:50,2:4].cov()

2         3
2  0.289567  0.087683
3  0.087683  0.040067

## $\Sigma_k(k=3)$

In [11]:
iris_train.iloc[50:75,2:4].cov()

2         3
2  0.320833  0.031000
3  0.031000  0.054067

## (b)

## $ d_k=|\Sigma_k|(k=1)$

In [12]:
d1 = np.linalg.det(iris_train.iloc[0:25,2:4].cov())
d1

0.0003933263888888887

## $ d_k=|\Sigma_k|(k=2)$

In [13]:
d2 = np.linalg.det(iris_train.iloc[25:50,2:4].cov())
d2

0.003913604166666682

## $ d_k=|\Sigma_k|(k=3)$

In [14]:
d3 = np.linalg.det(iris_train.iloc[50:75,2:4].cov())
d3

0.016385388888888883

## (c)

In [15]:
x=[4.4, 1.4]
L1x = sp.stats.multivariate_normal(u1, d1).pdf(x)
L1x

0.0

In [16]:
L2x = sp.stats.multivariate_normal(u2, d2).pdf(x)
L2x

9.78299676904275

In [17]:
L3x = sp.stats.multivariate_normal(u3, d3).pdf(x)
L3x

2.0504009744134528e-23

In [18]:
l1x = -np.log(L1x)
l1x

C:\Users\yaoqi\AppData\Local\Temp/ipykernel_584/877102990.py:1: RuntimeWarning: divide by zero encountered in log
  l1x = -np.log(L1x)


inf

In [19]:
l2x = -np.log(L2x)
l2x

-2.2806458552128177

In [20]:
l3x = -np.log(L3x)
l3x

52.24142176756453

## $P\{Label = k|\pmb{x}\} = P\{\pmb{x}|Label = k\}⋅P\{Label = k\}/P\{\pmb{x}\}$
## In this equation, the $P\{Label = k\}$ is constant to be 1/3 and the $P\{\pmb{x}\}$ is also constant.

## As stated by the mathematical rule, the minmum of $l_{k}(x)$ and maximum of $L_{k}(x)$ appear at $k==2$. This means $\pmb{x}=[4.4\ 1.4]^T$ belongs to Label 2.

In [21]:
u = iris_train.iloc[:,2:4].mean()
u

2    3.777333
3    1.230667
dtype: float64

In [22]:
d = np.linalg.det(iris_train.iloc[:,2:4].cov())
d

0.13534336815193665

## $P\{Label = 1|\pmb{x}\}=$

In [23]:
L1x * 1/3/sp.stats.multivariate_normal(u, d).pdf(x)

0.0

## $P\{Label = 2|\pmb{x}\}=$

In [24]:
L2x * 1/3/sp.stats.multivariate_normal(u, d).pdf(x)

12.912992548467937

## $P\{Label = 3|\pmb{x}\}=$

In [25]:
L3x * 1/3/sp.stats.multivariate_normal(u, d).pdf(x)

2.706411248928893e-23

## This still shows that the $\pmb{x}=[4.4\ 1.4]^T$ belongs to Label 2.

## (d)

In [26]:
iris_test['5'] = None

for i in range(iris_test.shape[0]):
    x = iris_test.iloc[i, 2:4]
    L1x = sp.stats.multivariate_normal(u1, d1).pdf(x)
    L2x = sp.stats.multivariate_normal(u2, d2).pdf(x)
    L3x = sp.stats.multivariate_normal(u3, d3).pdf(x)
    label = [L1x, L2x, L3x].index(max([L1x, L2x, L3x]))+1
    iris_test.iloc[i,5] = label

In [27]:
iris_test

0    1    2    3  4  5
24   4.8  3.4  1.9  0.2  1  1
29   4.7  3.2  1.6  0.2  1  1
14   5.8  4.0  1.2  0.2  1  1
13   4.3  3.0  1.1  0.1  1  1
9    4.9  3.1  1.5  0.1  1  1
..   ...  ...  ...  ... .. ..
106  4.9  2.5  4.5  1.7  3  2
131  7.9  3.8  6.4  2.0  3  3
119  6.0  2.2  5.0  1.5  3  3
112  6.8  3.0  5.5  2.1  3  3
103  6.3  2.9  5.6  1.8  3  3

[75 rows x 6 columns]

In [28]:
confm = pd.DataFrame(columns = ["1", "2", "3"], index = ["1", "2", "3"])
confm.columns.name = 'Ground truth\classified'
confm

Ground truth\classified    1    2    3
1                        NaN  NaN  NaN
2                        NaN  NaN  NaN
3                        NaN  NaN  NaN

In [29]:
for i in range(3):
    for j in range(3):
        gtruth = iris_test[iris_test.iloc[:,4] == i+1]
        gtruth = gtruth[gtruth.iloc[:,5] == j+1]
        confm.iloc[i,j] = gtruth.shape[0]
confm

Ground truth\classified   1   2   3
1                        25   0   0
2                         0  24   1
3                         0   1  24

## Seeing the confusion matrix above, 25 iris with label 1 are rightly classified into 1. 16 iris with label 2 are classified rightly and 9 are wrongly classified, while all iris with label 3 are classified into right label.

## Problem 2
## (a)

In [30]:
X = np.mat([[1, 1], [2, 1], [3, 1], [4, 1]])
X

matrix([[1, 1],
        [2, 1],
        [3, 1],
        [4, 1]])

## $X^{T}X$

In [31]:
X.T.dot(X)

matrix([[30, 10],
        [10,  4]])

## $(X^{T}X)^{-1}$

In [32]:
np.linalg.inv(X.T.dot(X))

matrix([[ 0.2, -0.5],
        [-0.5,  1.5]])

## $X^{*}=(X^{T}X)^{-1}X^{T}$

In [33]:
Xx = np.linalg.inv(X.T.dot(X)).dot(X.T)
Xx

matrix([[-0.3, -0.1,  0.1,  0.3],
        [ 1. ,  0.5,  0. , -0.5]])

## (b)

In [34]:
A = Xx.dot(X)
A

matrix([[ 1.00000000e+00, -2.77555756e-16],
        [ 4.44089210e-16,  1.00000000e+00]])

In [35]:
B = X.dot(Xx)
B

matrix([[ 0.7,  0.4,  0.1, -0.2],
        [ 0.4,  0.3,  0.2,  0.1],
        [ 0.1,  0.2,  0.3,  0.4],
        [-0.2,  0.1,  0.4,  0.7]])

## (c)

In [36]:
y = np.mat([[1.8], [3.9], [5.2], [6.5]])
y

matrix([[1.8],
        [3.9],
        [5.2],
        [6.5]])

In [37]:
w = Xx.dot(y)
w

matrix([[1.54],
        [0.5 ]])

In [38]:
e = X.dot(w) - y
e

matrix([[ 0.24],
        [-0.32],
        [-0.08],
        [ 0.16]])

In [39]:
fw = np.linalg.norm(e, ord=2)
fw**2

0.19199999999999978