In [53]:
import numpy  as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
import sa
from random import choice, shuffle, sample, uniform
import math

In [54]:
tmp_list = []
with open('p7.txt', 'r') as file:
    for row in file:
        tmp_list.append(row.split())
distance = np.array(tmp_list).astype('float')
print(distance)

N = len(distance)
print(N)
start = 0

[[0.     0.6347 0.3231 0.251  0.2727 0.4968 0.5144 0.2105]
 [0.6347 0.     0.9375 0.5755 0.6472 0.2507 0.2808 0.7916]
 [0.3231 0.9375 0.     0.4092 0.3636 0.8195 0.7615 0.1527]
 [0.251  0.5755 0.4092 0.     0.073  0.5427 0.3577 0.2577]
 [0.2727 0.6472 0.3636 0.073  0.     0.6136 0.4204 0.2187]
 [0.4968 0.2507 0.8195 0.5427 0.6136 0.     0.4048 0.6918]
 [0.5144 0.2808 0.7615 0.3577 0.4204 0.4048 0.     0.6088]
 [0.2105 0.7916 0.1527 0.2577 0.2187 0.6918 0.6088 0.    ]]
8


### Question 7a

In [55]:
def SimulatedAnnealing(curnode, nextnodeList, t):

    if nextnodeList == None or len(nextnodeList) < 1:
        return 0
    maxcost = sys.maxsize
    retnode = 0

    for node in nextnodeList:
        t *= 0.98
        if distance[curnode][node] < maxcost:
            maxcost = distance[curnode][node]
            retnode = node
        else:
            r = math.exp((distance[curnode][node] - maxcost)/t)
            if distance[curnode][node] > maxcost and t > t_min and math.exp((distance[curnode][node] - maxcost) / t) > r:
                retnode = node
                maxcost = distance[curnode][node]
                return(retnode, maxcost, t)

    return (retnode, maxcost, t)

In [56]:
num_cities = len(distance)
indexList = [i for i in range(num_cities)]
tripList = []

# Starting from city 1:
tripList.append(0)
indexList.remove(0)

mincost = 0
count = 0
t = 100
t_min = 50

while count < num_cities-1:
    count += 1
    leftItemNum = len(indexList)
    if leftItemNum < 2:
        leftItemNum = 1
    else:
        leftItemNum -= 1
    
    nextnodeList = sample(indexList, leftItemNum)
    
    if len(tripList) == 0:
        item = choice(nextnodeList)
        tripList.append(item)
        indexList.remove(item)
        mincost = 0
        continue
    
    curnode = tripList[len(tripList) - 1]
    nextnode, maxcost, t = SimulatedAnnealing(curnode, indexList, t)

    mincost += maxcost
    indexList.remove(nextnode)
    tripList.append(nextnode)

In [57]:
tripNames = np.array(tripList) + 1
print("For TSP of cities 1 to 8:")
print("Optimum tour = ", tripNames)
print("Minimum trip length = ", mincost)

For TSP of cities 1 to 8:
Optimum tour =  [1 8 3 5 4 7 2 6]
Minimum trip length =  1.6889999999999996
