In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv('p5train.csv',header=None).to_numpy()

In [3]:
test = pd.read_csv('p5test.csv',header=None).to_numpy()

In [4]:
from sklearn import svm

In [5]:
clf = svm.SVC(kernel='linear',C=0.25)
clf.fit(train[:,0:8], train[:,8])

SVC(C=0.25, kernel='linear')

In [6]:
yhat = clf.predict(train[:,0:8])

In [7]:
yhat

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
# confusion matrix
cmat = np.zeros((2,2))
for i in range(train[:,8].shape[0]):
    cmat[int((yhat[i]+1)/2),int((train[i,8]+1)/2)] += 1
    
print('The confusion matrix of training set is:')
print(cmat)

The confusion matrix of training set is:
[[65.  0.]
 [ 0. 75.]]


In [9]:
yhat = clf.predict(test[:,0:8])

In [10]:
yhat

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
# confusion matrix
cmat = np.zeros((2,2))
for i in range(test[:,8].shape[0]):
    cmat[int((yhat[i]+1)/2),int((test[i,8]+1)/2)] += 1
    
print('The confusion matrix of testing set is:')
print(cmat)

The confusion matrix of testing set is:
[[28.  0.]
 [ 0. 32.]]


In [12]:
nsv = clf.n_support_       # number of support vectors in class 0 and class 1
print("Number of Support Vectors for each class: " + str(nsv))

Number of Support Vectors for each class: [4 5]


In [13]:
f = clf.dual_coef_        # this is the vector f = alpha.*d
print("f: " + str(f))

f: [[-0.06532213 -0.13230728 -0.00409878 -0.04775899  0.08876163  0.08683246
   0.00932338  0.05316429  0.01140542]]


In [14]:
i0 = clf.support_          # indices of support vectors
print("Index of chosen Support Vectors: " + str(i0))

Index of chosen Support Vectors: [ 17  47  51  63  70 100 102 124 137]


In [15]:
sv = clf.support_vectors_  # Support Vectors
print("Chosen Support Vectors: \n" + str(sv))

Chosen Support Vectors: 
[[-17.12136701  11.12136701 -20.69658248  -5.08091134   1.14159484
   -0.08091134  19.16182268   1.26296185]
 [  6.87863299   4.12136701   6.30341752  -7.08091134   0.14159484
    5.91908866  -6.83817732   0.26296185]
 [ 10.87863299  -6.87863299   2.30341752  -2.08091134  16.14159484
    2.91908866   8.16182268  -2.73703815]
 [ -6.12136701   1.12136701  -2.69658248  -6.08091134   5.14159484
    6.91908866 -13.83817732  11.26296185]
 [-14.87863299  18.87863299 -21.30341752 -15.91908866  11.85840516
    3.08091134  -4.16182268  -0.26296185]
 [  7.12136701  -9.12136701   3.69658248  -0.91908866 -14.14159484
    2.08091134   5.83817732   5.73703815]
 [  1.12136701  -5.12136701  -3.30341752 -10.91908866  -7.14159484
   -5.91908866  -2.16182268   5.73703815]
 [  9.12136701   3.87863299   7.69658248   4.08091134   8.85840516
   12.08091134 -10.16182268  -2.26296185]
 [-10.87863299   1.87863299  10.69658248  -5.91908866   0.85840516
   16.08091134  -8.16182268 -11.2629

In [17]:
print("Labels of Support Vectors: " + str(train[:,8][i0]))

Labels of Support Vectors: [-1. -1. -1. -1.  1.  1.  1.  1.  1.]
